default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Activek123?
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: CodeAlpha_TaskScheduler_Backend_development

test:
  <<: *default
  database: CodeAlpha_TaskScheduler_Backend_test

production:
  <<: *default
  database: CodeAlpha_TaskScheduler_Backend_production
  username: CodeAlpha_TaskScheduler_Backend
  password: <%= ENV["CODEALPHA_TASKSCHEDULER_BACKEND_DATABASE_PASSWORD"] %>
